### Criar usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Pedro",
  "email": "pedro@email.com"
}

###

### Buscar usuário por ID
GET http://localhost:8080/users/1